const toyData = [
    {
        id: 1,
        category: "Marvel",
        name: "Iron Man MK-85",
        price: "$85", 
        brand: "MARVEL STUDIOS", 
        material: "Die-cast Metal", 
        weight: "800g", 
        battery: "Yes", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfC5SKthFm8QtUZXzlbMhswIU3f-J8u12iag&s" 
    },
    {
        id: 2,
        category: "Marvel",
        name: "Captain America Shield",
        price: "$50", 
        brand: "HASBRO TOYS", 
        material: "ABS Plastic", 
        weight: "1.2kg", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAVf18z5xrrLQabVgdxvvdDwj444KK4MX95Q&s" 
    },
    {
        id: 3,
        category: "Marvel",
        name: "Spider-Man No Way Home",
        price: "$220", 
        brand: "HOT TOYS", 
        material: "Fabric/PVC", 
        weight: "600g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFg_rCU6yTdp_2bidcQLaLcmwHrhoH1At6yw&s" 
    },
    {
        id: 4,
        category: "Marvel",
        name: "Thor Mjolnir Hammer",
        price: "$45", 
        brand: "MATTEL", 
        material: "Hard Plastic", 
        weight: "900g", 
        battery: "Yes", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrKpVGUl3OIl3K6I1X9Pbzlwe9BoT3T8Ef1g&s" 
    },
    {
        id: 5,
        category: "Marvel",
        name: "Black Panther Claw",
        price: "$30", 
        brand: "MARVEL STUDIOS", 
        material: "Soft PVC", 
        weight: "350g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkgQfZNfLe2CqTy6Wu7c-ak27EljGXF2sitA&s" 
    },
    {
        id: 6,
        category: "Marvel",
        name: "Hulk Smash Fists",
        price: "$25", 
        brand: "HASBRO TOYS", 
        material: "Foam", 
        weight: "500g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJvm9CnJzfzDkgDDllHHyhxZniTh2VcERJJQ&s" 
    },
    {
        id: 7,
        category: "Marvel",
        name: "Black Widow Figure",
        price: "$180", 
        brand: "HOT TOYS", 
        material: "Fabric/Resin", 
        weight: "400g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRoDqrLLE5u_A_xLrPNXJlJc-8KbfAxttqTw&s" 
    },
    {
        id: 8,
        category: "Marvel",
        name: "Sanctum Sanctorum",
        price: "$250", 
        brand: "LEGO GROUP", 
        material: "ABS", 
        weight: "2.5kg", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQW7zSZfJaez62NF6HPxzeS93oxrJYlC_aPw&s" 
    },
    {
        id: 9,
        category: "Marvel",
        name: "Infinity Gauntlet",
        price: "$100", 
        brand: "MARVEL STUDIOS", 
        material: "PVC/Electronics", 
        weight: "1.5kg", 
        battery: "Yes", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2FulV_tgHs75XsiTOj7plm6bxW-bq9KlIA&s" 
    },
    {
        id: 10,
        category: "Marvel",
        name: "Dancing Baby Groot",
        price: "$35", 
        brand: "MATTEL", 
        material: "Plastic", 
        weight: "300g", 
        battery: "Yes", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpPlswZF5LWiHBZWBMLNLluYe-yYAzoelm_A&s" 
    },
    {
        id: 11,
        category: "Marvel",
        name: "Ant-Man Tech Helmet",
        price: "$70", 
        brand: "HASBRO TOYS", 
        material: "Plastic", 
        weight: "850g", 
        battery: "Yes", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzf_RXKFJV9rELG4FvunPLaB8D_0DRwEtMg&s"
    },
    {      
        id: 12,
        category: "Marvel",
        name: "Scarlet Witch (Multiverse)",
        price: "$210", 
        brand: "HOT TOYS", 
        material: "Resin/Fabric", 
        weight: "500g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyEXclQiqExRfltK1P-e8PjJ-yChFHodtyWA&s" 
    },
    { 
        id: 13, 
        name: "Roman Reigns Elite", 
        category: "WWE",
        price: "$25", 
        brand: "MATTEL", 
        material: "Vinyl/Plastic", 
        weight: "450g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1hZT2sAEqqaetj8QhBXDNBH1CadeTgaZmXyhtCsMU6Q&s" 
    },
    { 
        id: 14, 
        name: "John Cena Basic", 
        category: "WWE",
        price: "$18", 
        brand: "MATTEL", 
        material: "Plastic", 
        weight: "400g", 
        battery: "No", 
        img: "https://cdn.1001hobbies.com/2451278-large_default/mattel-matthvf92-wwe-ultimate-edition-john-cena-figure-15-cm.jpg" 
    },
    { 
        id: 15, 
        name: "WWE Title Belt", 
        category: "WWE",
        price: "$40", 
        brand: "WWE SHOP", 
        material: "Faux Leather/Plastic", 
        weight: "1.1kg", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9eSJ_3tCN4Y6xL4kM8D5UtxnQ6NwSRQVx0A&s" 
    },
    { 
        id: 16, 
        name: "Rey Mysterio Ultimate", 
        category: "WWE",
        price: "$32", 
        brand: "MATTEL", 
        material: "Highly Flexible Plastic", 
        weight: "380g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf-q92XNHL84JbneR7-ZS8Cgs8vr64ga1n0g&s" 
    },
    { 
        id: 17, 
        name: "The Rock Elite", 
        category: "WWE",
        price: "$28", 
        brand: "MATTEL", 
        material: "Vinyl", 
        weight: "440g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWTkJ4jJdT24JDe7SxVK6KkQ7AUwsQgWW3xw&s" 
    },
    { 
        id: 18, 
        name: "Seth Rollins Elite", 
        category: "WWE",
        price: "$24", 
        brand: "MATTEL", 
        material: "Plastic/Fabric", 
        weight: "420g", 
        battery: "No", 
        img: "https://static.thcdn.com/images/large/original//productimg/1600/1600/16758987-1745242290193152.jpg" 
    },
    { 
        id: 19, 
        name: "Brock Lesnar Ultimate", 
        category: "WWE",
        price: "$35", 
        brand: "MATTEL", 
        material: "Hard Rubber/Plastic", 
        weight: "500g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkYL9JxGHaA4dShbD6rOOQOBS6Nt378CdNSg&s" 
    },
    { 
        id: 20, 
        name: "Cody Rhodes Elite", 
        category: "WWE",
        price: "$26", 
        brand: "MATTEL", 
        material: "Plastic/Soft Goods", 
        weight: "430g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX5DvA3UmDJm7an10D82Kg--pV5Sx5Zy6VNw&s" 
    },
    { 
        id: 21, 
        name: "Undertaker Elite", 
        category: "WWE",
        price: "$30", 
        brand: "MATTEL", 
        material: "Vinyl/Fabric", 
        weight: "480g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV02uam9ny7a4shC_I39Pq5duwvGm7EL5hfQ&s" 
    },
    { 
        id: 22, 
        name: "Randy Orton Elite", 
        category: "WWE",
        price: "$22", 
        brand: "MATTEL", 
        material: "Plastic", 
        weight: "410g", 
        battery: "No", 
        img: "https://tools.toywiz.com/_images/_webp/_products/lg/wweelite34randyorton.webp" 
    },
    { 
        id: 23, 
        name: "Becky Lynch Elite", 
        category: "WWE",
        price: "$23", 
        brand: "MATTEL", 
        material: "Vinyl/Plastic", 
        weight: "390g", 
        battery: "No", 
        img: "https://m.media-amazon.com/images/I/71MsjIbSUFL._AC_UF894,1000_QL80_.jpg" 
    },
    { 
        id: 24, 
        name: "Triple H Ultimate", 
        category: "WWE",
        price: "$33", 
        brand: "MATTEL", 
        material: "Plastic/Die-cast accessories", 
        weight: "460g", 
        battery: "No", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOdxYz1oc52lVHlT0D7949xPU4-aFxXYjFnQ&s" 
    }
];